apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook
  labels:
    app: phonebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
      - name: phonebook-container
        image: murali90102/phonebook:10
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phonebook
  labels:
    app: phonebook
spec:
  selector:
    app: phonebook

  type: NodePort
  ports:
  - nodePort: 31111
    port: 80
    targetPort: 80
