version: '3'
services:
  php:
    image: phphttpd:2
    container_name: phphttpd
    ports:
      - "8087:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=phpcrud
 
